name: CI/CD DevOps App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install deps
      run: npm ci
      working-directory: backend

    - name: Lint
      run: npm run lint
      working-directory: backend

    - name: Test
      run: npm test
      working-directory: backend

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-backend:latest ./backend

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-backend:latest
